name: Unit Tests
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  tests:
    name: Flow CLI Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: "true"
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20
    - name: Install Flow CLI
      run: bash -ci "$(curl -fsSL https://raw.githubusercontent.com/onflow/flow-cli/master/install.sh)" -- v1.9.2-stable-cadence.1
    - name: Run tests
      run: flow test --cover --covercode="contracts" test/*_test.cdc
